name: Linux Build Test

on: push
jobs:
  cmake-build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Setup cmake
      - uses: lukka/get-cmake@latest

      - name: install-conan
        shell: bash
        run: pip install conan

      - name: create-conan-profile
        shell: bash
        # Generates default profile detecting GCC and sets old ABI
        run: conan profile new default --detect;

      - name: update-conan-profile
        shell: bash
        run: echo [conf]\ntools.system.package_manager:sudo=True\ntools.system.package_manager:mode=install >> ~/.conan/profiles/default

      # Build project
      - name: build
        shell: bash
        run: >
          sudo apt-get install libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev
          chmod u+x build.sh;
          export CONAN_SYSREQUIRES_MODE="enabled";
          export CONAN_SYSREQUIRES_SUDO="1";
          ./build.sh

      - name: verify-files
        shell: bash
        run: >
          rm ./build/bin/Client
          rm ./build/bin/Server
