name: MacOS Build Test

on: push
jobs:
  cmake-build:
    runs-on: macos-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Setup cmake
      - uses: lukka/get-cmake@latest

      - name: install-conan
        shell: bash
        run: >
          pip3 install conan;
          PATH=$PATH:/usr/local/bin;

      - name: create-conan-profile
        shell: bash
        # Generates default profile detecting GCC and sets old ABI
        run: conan profile new default --detect;

      # Build project
      - name: build
        shell: bash
        run: >
          conan profile update conf.tools.system.package_manager:mode=install default;
          conan profile update conf.tools.system.package_manager:sudo=True default;
          mkdir build;
          make build;

      - name: verify-files
        shell: bash
        run: >
          rm ./bin/Client;
          rm ./bin/Server;
