name: Windows Build Test

on: push
jobs:
  cmake-build:
    runs-on: windows-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Setup cmake
      - uses: lukka/get-cmake@latest

      - name: install-conan
        shell: powershell
        run: pip install conan

      - name: create-conan-profile
        shell: powershell
        # Generates default profile detecting GCC and sets old ABI
        run: >
          conan profile new default --detect;
          conan profile update conf.tools.system.package_manager:mode=install default;
          conan profile update conf.tools.system.package_manager:sudo=True default;


      # Build project
      - name: build
        shell: powershell
        run: >
          conan install conanfile.txt -if build --build=missing;
          cmake -S . -B build;
          cmake --build build;

      - name: verify-files
        shell: bash
        run: >
          rm ./build/bin/Client;
          rm ./build/bin/Server;
