name: Windows Build Test

on: push
jobs:
  cmake-build:
    runs-on: windows-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Setup cmake
      - uses: lukka/get-cmake@latest

      - name: install-conan
        shell: powershell
        run: pip install conan
