name: CMake Build Test

on: push
jobs:
  cmake-build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Setup cmake
      - uses: lukka/get-cmake@latest

      - name: install-conan
        shell: bash
        run: pip install conan

      - name: create-conan-profile
        shell: bash
        # Generates default profile detecting GCC and sets old ABI
        run: conan profile new default --detect;

      - name: update-conan-profile
        shell: bash
        run: >
              conan config set tools.system.package_manager:mode=install;
              conan config set tools.system.package_manager:sudo=True;

      # Build project
      - name: build
        shell: bash
        run: chmod u+x setup.sh; ./setup.sh;