name: CMake Build Test

on: push
jobs:
  cmake-build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Setup cmake
      - uses: lukka/get-cmake@latest

      # Build project
      - name: run-cmake
        uses: lukka/run-cmake@v10.0
