name: CMake Build Test

on: push
jobs:
  cmake-build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Setup cmake
      - uses: lukka/get-cmake@latest

      - name: install-conan
        shell: bash
        run: pip install conan

      - name: update-conan-profile
        shell: bash
        run: conan profile update settings.compiler='other' default

      # Build project
      - name: run-cmake
        shell: bash
        run: cmake -B build/ -S .

      - name: build-cmake
        shell: bash
        run: cmake --build build/