# This is a basic workflow to help you get started with Actions

name: Github Epitech Sync

on: push

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:mindoodoo/R-Type.git"
          source_branch: "main"
          destination_repo: "git@github.com:EpitechPromo2025/B-CPP-500-BER-5-1-rtype-nicolas.lattemann.git"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}